# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_dnnc')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_dnnc')
    _dnnc = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_dnnc', [dirname(__file__)])
        except ImportError:
            import _dnnc
            return _dnnc
        try:
            _mod = imp.load_module('_dnnc', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _dnnc = swig_import_helper()
    del swig_import_helper
else:
    import _dnnc
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _dnnc.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _dnnc.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _dnnc.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _dnnc.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _dnnc.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _dnnc.SwigPyIterator_equal(self, x)

    def copy(self):
        return _dnnc.SwigPyIterator_copy(self)

    def next(self):
        return _dnnc.SwigPyIterator_next(self)

    def __next__(self):
        return _dnnc.SwigPyIterator___next__(self)

    def previous(self):
        return _dnnc.SwigPyIterator_previous(self)

    def advance(self, n):
        return _dnnc.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _dnnc.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _dnnc.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _dnnc.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _dnnc.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _dnnc.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _dnnc.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _dnnc.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

SHARED_PTR_DISOWN = _dnnc.SHARED_PTR_DISOWN
class FLOAT_TENSOR(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FLOAT_TENSOR, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FLOAT_TENSOR, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _dnnc.new_FLOAT_TENSOR(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _dnnc.delete_FLOAT_TENSOR
    __del__ = lambda self: None

    def load(self, data):
        return _dnnc.FLOAT_TENSOR_load(self, data)

    def to_string(self):
        return _dnnc.FLOAT_TENSOR_to_string(self)

    def size(self):
        return _dnnc.FLOAT_TENSOR_size(self)

    def rank(self):
        return _dnnc.FLOAT_TENSOR_rank(self)

    def shape(self):
        return _dnnc.FLOAT_TENSOR_shape(self)

    def reshape(self, new_shape):
        return _dnnc.FLOAT_TENSOR_reshape(self, new_shape)

    def __call__(self, *args):
        return _dnnc.FLOAT_TENSOR___call__(self, *args)

    def dtype(self):
        return _dnnc.FLOAT_TENSOR_dtype(self)

    def empty(self):
        return _dnnc.FLOAT_TENSOR_empty(self)

    def to_proto(self):
        return _dnnc.FLOAT_TENSOR_to_proto(self)
FLOAT_TENSOR_swigregister = _dnnc.FLOAT_TENSOR_swigregister
FLOAT_TENSOR_swigregister(FLOAT_TENSOR)


def make_tensor(x, y=0, z=0, w=0):
    return _dnnc.make_tensor(x, y, z, w)
make_tensor = _dnnc.make_tensor

def multiply(a, b):
    return _dnnc.multiply(a, b)
multiply = _dnnc.multiply
# This file is compatible with both classic and new-style classes.


